Check if XDG_RUNTIME_DIR does exist
Check if XDG_RUNTIME_DIR does exist and issue a warning and exit 1
if it does not.

diff --git a/scripts/startxfce4.in b/scripts/startxfce4.in
--- a/scripts/startxfce4.in
+++ b/scripts/startxfce4.in
@@ -67,6 +67,10 @@ then
           fi
         fi
       fi
+      if [ ! -e "${XDG_RUNTIME_DIR}" ]; then
+         echo "XDG_RUNTIME_DIR is invalid or does not exist!"
+         exit 1
+      fi
       # freedesktop specifications mandate that the definition
       # of XDG_SESSION_TYPE should be respected
       XDG_SESSION_TYPE="wayland"
