Exit with error, if there is no X connection

diff --git a/scripts/xflock4 b/scripts/xflock4
--- a/scripts/xflock4
+++ b/scripts/xflock4
@@ -21,6 +21,12 @@
 #  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
+xset q >/dev/null 2>&1 ||
+if [ 1 -eq "$?" ]; then
+    >&2 printf '%s\n' 'Error: No X connection'
+    exit 1
+fi
+
 # Prevent unintentional recursive calling of xflock4.
 dirname=xflock4-lock
 if [ -n "${XDG_RUNTIME_DIR:+x}" ]; then
