Prevent infinite recursive calls of xflock4 (#120)
xfce4-session property /general/LockCommand may be set to run xflock4,
so the script becomes recursive. Prevent such recursion by using
a lock directory.

Note that the lock directory should be removed when starting a session
in case it exists due to e.g. power failure; not all systems clear
/tmp on boot.

diff --git a/scripts/xflock4 b/scripts/xflock4
--- a/scripts/xflock4
+++ b/scripts/xflock4
@@ -21,6 +21,13 @@
 #  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
+lockdir=/tmp/xflock4-lock
+if ! mkdir "$lockdir" 2>/dev/null; then
+    >&2 printf '%s\n' 'Error: xflock4 running already'
+    exit 1
+fi
+trap 'rm -rf "$lockdir"; trap - EXIT' HUP INT TERM EXIT
+
 # Wait a bit so that user have time to raise finger from a key if
 # the script is run in terminal.
 [ -t 0 ] && sleep 1
