Exit with error, if there is no X connection

diff --git a/scripts/xflock4 b/scripts/xflock4
--- a/scripts/xflock4
+++ b/scripts/xflock4
@@ -21,6 +21,12 @@
 #  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
+xset q >/dev/null 2>&1 ||
+if [ 1 -eq "$?" ]; then
+    >&2 printf '%s\n' 'Error: No X connection'
+    exit 1
+fi
+
 # Wait a bit so that user have time to raise finger from a key if
 # the script is run in terminal.
 [ -t 0 ] && sleep 1
