Prevent unintentional recursive calls of xflock4 (#120)
xfce4-session property /general/LockCommand may be set to run xflock4,
so the script becomes recursive. Prevent such recursion by using
a lock directory.

The lock directory is created under $XDG_RUNTIME_DIR, if that variable
is set. Otherwise a warning message is displayed and the lock directory
is created under /tmp. See
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
about the former directory. If the latter is preferred, system
administrator should ensure sticky bit is set for /tmp, and remove the
possible stale lock directory on session start, if /tmp is not cleared
otherwise on boot.

diff --git a/scripts/xflock4 b/scripts/xflock4
--- a/scripts/xflock4
+++ b/scripts/xflock4
@@ -28,6 +28,23 @@
 # Use a custom lock command, if given.
 LOCK_CMD=$(xfconf-query -c xfce4-session -p /general/LockCommand || :)
 [ -n "$LOCK_CMD" ] && {
+    # Prevent unintentional recursive calling of xflock4.
+    dirname=xflock4-lock
+    if [ -n "${XDG_RUNTIME_DIR:+x}" ]; then
+        lockdir=$XDG_RUNTIME_DIR/$dirname
+    else
+        fallback_basedir=/tmp
+        # Create user specific lock directory
+        lockdir=$fallback_basedir/${dirname}-$(id -u -r)
+        >&2 printf '%s %s %s\n' 'Warning: XDG_RUNTIME_DIR not set.' \
+        'Creating a lock directory under' "$fallback_basedir"
+    fi
+    if ! mkdir "$lockdir" 2>/dev/null; then
+        >&2 printf '%s\n' 'Error: recursive lock'
+        exit 1
+    fi
+    trap 'rm -rf "$lockdir"; trap - EXIT' HUP INT TERM EXIT
+
     exit_code=0
     /bin/sh -c "$LOCK_CMD" && exit || {
         exit_code=$?
