xflock4: Improve support for lockers (#17)
Run the shell command read from Xfconf property /general/LockCommand
in separate shell, if the property exists and is non-null. That way the
command can not change variables of xflock4 or use its functions. The
property can be a complex shell one-liner that is encapsulated within
xflock4. If you want to use a non-forking locker, you should run it in
background by adding '&' after the command in the line to make it fork
anyway so that xflock4 exits before unlocking. If the one-liner fails,
xflock4 fails, with its exit status. Note that if you put a locker in
background, its exit status will not be received.

xscreensaver-command can take GNU style options so it can be called
from the loop.

'gnome-screensaver-command --lock' returns always 0; tested on
gnome-screensaver 3.6.1; the project is unmaintained, so drop
explicit support for that.

Add explicit support for light-locker, as it is integrated with
xfce4-power-manager. (light-locker pauses audio while locking)

Remove hard-coded fallback lockers because user can specify which
locker to use by LockCommand property.

Xflock4 (!20)

diff --git a/scripts/xflock4 b/scripts/xflock4
--- a/scripts/xflock4
+++ b/scripts/xflock4
@@ -4,7 +4,7 @@
 #
 #  Copyright (C) 2011 Guido Berhoerster (guido+xfce.org@berhoerster.name)
 #  Copyright (C) 2015, 2018 Simon Steinbeiß (simon@xfce.org)
-#  Copyright (C) 2011 Jarno Suni (8@iki.fi)
+#  Copyright (C) 2011, 2022 Jarno Suni (8@iki.fi)
 #
 #  This program is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -21,34 +21,27 @@
 #  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #
 
-# First test for the command set in the session's xfconf channel
-LOCK_CMD=$(xfconf-query -c xfce4-session -p /general/LockCommand)
+# Use a custom lock command, if given.
+LOCK_CMD=$(xfconf-query -c xfce4-session -p /general/LockCommand || :)
+[ -n "$LOCK_CMD" ] && {
+    exit_code=0
+    /bin/sh -c "$LOCK_CMD" && exit || {
+        exit_code=$?
+        >&2 printf "'%s' exited with status %d\n" "$LOCK_CMD" $exit_code
+        exit $exit_code
+    }
+}
 
-# Lock by xscreensaver or gnome-screensaver, if a respective daemon is running
+# Else try certain screensavers for locking.
 for lock_cmd in \
-    "$LOCK_CMD" \
-    "xfce4-screensaver-command --lock" \
-    "xscreensaver-command -lock" \
-    "gnome-screensaver-command --lock"
+    xscreensaver-command \
+    light-locker-command \
+    xfce4-screensaver-command
 do
-    if [ ! -z "$lock_cmd" ]; then
-        $lock_cmd >/dev/null 2>&1 && exit
-    fi
+    # To redirect stdin to /dev/null is needed at least for xscreensaver
+    # to not have 1 s delay when invoked on terminal.
+    ${lock_cmd} --lock </dev/null 2>/dev/null && exit
 done
 
-# else run another access locking utility, if installed
-for lock_cmd in \
-  "xlock -mode blank" \
-  "slock"
-  do
-    set -- $lock_cmd
-    if command -v -- $1 >/dev/null 2>&1; then
-        $lock_cmd >/dev/null 2>&1 &
-	# turn off display backlight:
-	xset dpms force off
-        exit
-    fi
-done
-
-# else access locking failed
+# Else access locking failed.
 exit 1
