Let xfce4-session handle the dbus-launch checking.
This makes it easier to start a fully working session
with only xfce4-session.

diff --git a/scripts/xinitrc.in.in b/scripts/xinitrc.in.in
--- a/scripts/xinitrc.in.in
+++ b/scripts/xinitrc.in.in
@@ -56,11 +56,6 @@ export GLADE_CATALOG_PATH
 export GLADE_PIXMAP_PATH
 export GLADE_MODULE_PATH
 
-# Export GTK_PATH so that GTK+ can find the Xfce theme engine
-# https://bugzilla.xfce.org/show_bug.cgi?id=7483
-#GTK_PATH="$GTK_PATH:@_libdir_@/gtk-2.0"
-#export GTK_PATH
-
 # For now, start with an empty list
 XRESOURCES=""
 
@@ -89,17 +84,6 @@ cat /dev/null $XRESOURCES | xrdb -nocpp -merge -
 # load local modmap
 test -r $HOME/.Xmodmap && xmodmap $HOME/.Xmodmap
 
-# Use dbus-launch if installed.
-if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
-    if which dbus-launch >/dev/null 2>&1; then
-		eval `dbus-launch --sh-syntax --exit-with-session`
-        # some older versions of dbus don't export the var properly
-        export DBUS_SESSION_BUS_ADDRESS
-    else
-        echo "Could not find dbus-launch; Xfce will not work properly" >&2
-	fi
-fi
-
 # Run xfce4-session if installed
 if which xfce4-session >/dev/null 2>&1; then
     xfce4-session
@@ -120,6 +104,16 @@ fi
 
 ##################
 
+# Use dbus-launch if installed.
+if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
+  if which dbus-launch >/dev/null 2>&1; then
+    eval `dbus-launch --sh-syntax --exit-with-session`
+    # some older versions of dbus don't export the var properly
+    export DBUS_SESSION_BUS_ADDRESS
+  else
+    echo "Could not find dbus-launch; Xfce will not work properly" >&2
+    fi
+fi
 
 # this is only necessary when running w/o xfce4-session
 xsetroot -solid black -cursor_name watch
