Added popup menu to the splash theme list, also added the possiblity to do XDS (XDirectSave) w/ rox (and probably other fms) to export themes. Logout icon is now themable. Added KDE/Gnome icon to the settings dialog. Other fixes.
(Old svn revision: 4594)

diff --git a/settings/scripts/xfsm-install-theme b/settings/scripts/xfsm-install-theme
--- a/settings/scripts/xfsm-install-theme
+++ b/settings/scripts/xfsm-install-theme
@@ -92,7 +92,7 @@ themename=`basename "${themedir}"`
    && tar cf - "${themename}/xfsm4/" \
     | (cd "${targetdir}" && tar xf -)) >/dev/null 2>&1
 if test $? -ne 0; then
-  echo "Unable to install the theme ${themename} from ${themebase} to ${targetdir}."
+  echo "Unable to install the theme ${themename} from ${themebase} to ${targetdir}." >&2
   leave 1
 fi
 
